2025-03-08 10:47:39,205 INFO: Application startup
2025-03-08 10:48:18,518 INFO: Application startup
2025-03-08 10:49:12,518 INFO: Received detect-emotion request: True
2025-03-08 10:49:12,522 INFO: Image data type: <class 'str'>, starts with: data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD
2025-03-08 10:49:12,544 INFO: Image shape: (240, 320, 3)
2025-03-08 10:49:13,212 INFO: Received detect-emotion request: True
2025-03-08 10:49:13,214 INFO: Image data type: <class 'str'>, starts with: data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD
2025-03-08 10:49:13,216 INFO: Image shape: (240, 320, 3)
2025-03-08 10:49:14,525 INFO: Received detect-emotion request: True
2025-03-08 10:49:14,525 INFO: Image data type: <class 'str'>, starts with: data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD
2025-03-08 10:49:14,526 INFO: Image shape: (240, 320, 3)
2025-03-08 10:49:14,572 INFO: Received detect-emotion request: True
2025-03-08 10:49:14,573 INFO: Image data type: <class 'str'>, starts with: data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD
2025-03-08 10:49:14,574 INFO: Image shape: (240, 320, 3)
2025-03-08 10:49:15,516 INFO: Received detect-emotion request: True
2025-03-08 10:49:15,518 INFO: Image data type: <class 'str'>, starts with: data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD
2025-03-08 10:49:15,519 INFO: Image shape: (240, 320, 3)
2025-03-08 10:49:16,043 INFO: Found 1 faces in image
2025-03-08 10:49:16,043 INFO: Found 1 faces in image
2025-03-08 10:49:16,043 INFO: Found 1 faces in image
2025-03-08 10:49:16,043 INFO: Found 1 faces in image
2025-03-08 10:49:16,043 INFO: Found 1 faces in image
2025-03-08 10:49:16,280 ERROR: Emotion detection error: 'Conv' object has no attribute 'bn'
2025-03-08 10:49:16,281 ERROR: Emotion detection error: 'Conv' object has no attribute 'bn'
2025-03-08 10:49:16,282 ERROR: Emotion detection error: 'Conv' object has no attribute 'bn'
2025-03-08 10:49:16,290 ERROR: Emotion detection error: 'Conv' object has no attribute 'bn'
2025-03-08 10:49:16,319 ERROR: Traceback (most recent call last):
  File "c:\Users\marwa\OneDrive\Desktop\StressDetection\app.py", line 171, in detect_emotion_from_image
    results = emotion_model.predict(source=target_img, verbose=True, conf=0.1)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\marwa\anaconda3\Lib\site-packages\ultralytics\engine\model.py", line 553, in predict
    self.predictor.setup_model(model=self.model, verbose=is_cli)
  File "C:\Users\marwa\anaconda3\Lib\site-packages\ultralytics\engine\predictor.py", line 310, in setup_model
    self.model = AutoBackend(
                 ^^^^^^^^^^^^
  File "C:\Users\marwa\anaconda3\Lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\marwa\anaconda3\Lib\site-packages\ultralytics\nn\autobackend.py", line 152, in __init__
    model = model.fuse(verbose=verbose)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\marwa\anaconda3\Lib\site-packages\ultralytics\nn\tasks.py", line 207, in fuse
    delattr(m, "bn")  # remove batchnorm
    ^^^^^^^^^^^^^^^^
  File "C:\Users\marwa\anaconda3\Lib\site-packages\torch\nn\modules\module.py", line 1799, in __delattr__
    super().__delattr__(name)
AttributeError: 'Conv' object has no attribute 'bn'

2025-03-08 10:49:16,320 ERROR: Traceback (most recent call last):
  File "c:\Users\marwa\OneDrive\Desktop\StressDetection\app.py", line 171, in detect_emotion_from_image
    results = emotion_model.predict(source=target_img, verbose=True, conf=0.1)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\marwa\anaconda3\Lib\site-packages\ultralytics\engine\model.py", line 553, in predict
    self.predictor.setup_model(model=self.model, verbose=is_cli)
  File "C:\Users\marwa\anaconda3\Lib\site-packages\ultralytics\engine\predictor.py", line 310, in setup_model
    self.model = AutoBackend(
                 ^^^^^^^^^^^^
  File "C:\Users\marwa\anaconda3\Lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\marwa\anaconda3\Lib\site-packages\ultralytics\nn\autobackend.py", line 152, in __init__
    model = model.fuse(verbose=verbose)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\marwa\anaconda3\Lib\site-packages\ultralytics\nn\tasks.py", line 207, in fuse
    delattr(m, "bn")  # remove batchnorm
    ^^^^^^^^^^^^^^^^
  File "C:\Users\marwa\anaconda3\Lib\site-packages\torch\nn\modules\module.py", line 1799, in __delattr__
    super().__delattr__(name)
AttributeError: 'Conv' object has no attribute 'bn'

2025-03-08 10:49:16,324 ERROR: Traceback (most recent call last):
  File "c:\Users\marwa\OneDrive\Desktop\StressDetection\app.py", line 171, in detect_emotion_from_image
    results = emotion_model.predict(source=target_img, verbose=True, conf=0.1)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\marwa\anaconda3\Lib\site-packages\ultralytics\engine\model.py", line 553, in predict
    self.predictor.setup_model(model=self.model, verbose=is_cli)
  File "C:\Users\marwa\anaconda3\Lib\site-packages\ultralytics\engine\predictor.py", line 310, in setup_model
    self.model = AutoBackend(
                 ^^^^^^^^^^^^
  File "C:\Users\marwa\anaconda3\Lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\marwa\anaconda3\Lib\site-packages\ultralytics\nn\autobackend.py", line 152, in __init__
    model = model.fuse(verbose=verbose)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\marwa\anaconda3\Lib\site-packages\ultralytics\nn\tasks.py", line 207, in fuse
    delattr(m, "bn")  # remove batchnorm
    ^^^^^^^^^^^^^^^^
  File "C:\Users\marwa\anaconda3\Lib\site-packages\torch\nn\modules\module.py", line 1799, in __delattr__
    super().__delattr__(name)
AttributeError: 'Conv' object has no attribute 'bn'

2025-03-08 10:49:16,352 ERROR: Traceback (most recent call last):
  File "c:\Users\marwa\OneDrive\Desktop\StressDetection\app.py", line 171, in detect_emotion_from_image
    results = emotion_model.predict(source=target_img, verbose=True, conf=0.1)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\marwa\anaconda3\Lib\site-packages\ultralytics\engine\model.py", line 553, in predict
    self.predictor.setup_model(model=self.model, verbose=is_cli)
  File "C:\Users\marwa\anaconda3\Lib\site-packages\ultralytics\engine\predictor.py", line 310, in setup_model
    self.model = AutoBackend(
                 ^^^^^^^^^^^^
  File "C:\Users\marwa\anaconda3\Lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\marwa\anaconda3\Lib\site-packages\ultralytics\nn\autobackend.py", line 152, in __init__
    model = model.fuse(verbose=verbose)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\marwa\anaconda3\Lib\site-packages\ultralytics\nn\tasks.py", line 207, in fuse
    delattr(m, "bn")  # remove batchnorm
    ^^^^^^^^^^^^^^^^
  File "C:\Users\marwa\anaconda3\Lib\site-packages\torch\nn\modules\module.py", line 1799, in __delattr__
    super().__delattr__(name)
AttributeError: 'Conv' object has no attribute 'bn'

2025-03-08 10:49:17,235 INFO: Detection results: 1
2025-03-08 10:49:17,235 INFO: Found 1 detections
2025-03-08 10:49:17,236 INFO: Class indices: [          0], Confidences: [    0.91853]
2025-03-08 10:49:17,237 INFO: Top class: 0.0, Labels: {0: 'angry', 1: 'disgust', 2: 'fear', 3: 'happy', 4: 'neutral', 5: 'sad', 6: 'surprise'}
2025-03-08 10:49:17,238 INFO: Detected emotion: angry with confidence 0.9185341000556946
2025-03-08 10:50:05,978 INFO: Application startup
2025-03-08 10:50:06,105 INFO: Received detect-emotion request: True
2025-03-08 10:50:06,106 INFO: Image data type: <class 'str'>, starts with: data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD
2025-03-08 10:50:06,108 INFO: Received detect-emotion request: True
2025-03-08 10:50:06,113 INFO: Image data type: <class 'str'>, starts with: data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD
2025-03-08 10:50:06,114 INFO: Received detect-emotion request: True
2025-03-08 10:50:06,115 INFO: Image data type: <class 'str'>, starts with: data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD
2025-03-08 10:50:06,118 INFO: Received detect-emotion request: True
2025-03-08 10:50:06,118 INFO: Image data type: <class 'str'>, starts with: data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD
2025-03-08 10:50:06,120 INFO: Received detect-emotion request: True
2025-03-08 10:50:06,121 INFO: Image data type: <class 'str'>, starts with: data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD
2025-03-08 10:50:06,123 INFO: Received detect-emotion request: True
2025-03-08 10:50:06,123 INFO: Image data type: <class 'str'>, starts with: data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD
2025-03-08 10:50:06,128 INFO: Image shape: (240, 320, 3)
2025-03-08 10:50:06,128 INFO: Image shape: (240, 320, 3)
2025-03-08 10:50:06,128 INFO: Image shape: (240, 320, 3)
2025-03-08 10:50:06,128 INFO: Image shape: (240, 320, 3)
2025-03-08 10:50:06,128 INFO: Image shape: (240, 320, 3)
2025-03-08 10:50:06,128 INFO: Image shape: (240, 320, 3)
2025-03-08 10:50:09,057 INFO: Found 1 faces in image
2025-03-08 10:50:09,057 INFO: Found 1 faces in image
2025-03-08 10:50:09,057 INFO: Found 1 faces in image
2025-03-08 10:50:09,057 INFO: Found 1 faces in image
2025-03-08 10:50:09,057 INFO: Found 1 faces in image
2025-03-08 10:50:09,057 INFO: Found 1 faces in image
2025-03-08 10:50:09,305 ERROR: Emotion detection error: 'Conv' object has no attribute 'bn'
2025-03-08 10:50:09,305 ERROR: Emotion detection error: 'Conv' object has no attribute 'bn'
2025-03-08 10:50:09,305 ERROR: Emotion detection error: 'Conv' object has no attribute 'bn'
